version: '3.9'

x-kong-config: &kong-env
  KONG_DATABASE: ${KONG_DATABASE:-off}

volumes:
  kong_prefix_vol:
    driver_opts:
     type: tmpfs
     device: tmpfs
  kong_tmp_vol:
    driver_opts:
     type: tmpfs
     device: tmpfs

networks:
  kong-net:
    external: false

# https://github.com/Kong/docker-kong/blob/master/compose/docker-compose.yml
services:
  kong:
    # image: "kong:3.2.2"
    build:
      context: .
    user: "kong"
    environment:
      <<: *kong-env
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:6000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:6001}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yml"
      KONG_LOG_LEVEL: info
      # KONG_PLUGINS: "bundled,upstream-auth-basic"
    networks:
      - kong-net
    ports:
      - "6001:6001/tcp"
      - "6000:6000/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    read_only: true
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
      - ./declarative:/opt/kong
      - ./conf:/etc/kong
  
  konga:
    image: pantsel/konga:next
    restart: always
    networks:
      - kong-net
    environment:
      NO_AUTH: true
      PORT: 1337
    ports:
      - "6002:1337"